name: setting up environment

on: [push]
    
env:
 username: ElytrA8
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           sudo apt-get install expect -y
           git config --global user.name "ElytrA8"
           git config --global user.email "manofuranium@gmail.com"           
       - name: cloning repo & setting up config
         continue-on-error: true
         run: |
           expect -c " 
           spawn git clone ${{ secrets.REPO }} source
           expect \"Username\"        
           send \"${{ secrets.GHUSER }}\r\"
           expect \"Password\"        
           send \"${{ secrets.GHPASS }}\r\"
           set timeout -1
           catch wait result
           interact"
       - name: compilation
         continue-on-error: true
         run: |
           cd source
           docker build . -t shell-bot
       - name: running Bot
         timeout-minutes: 340
         continue-on-error: true
         run: |
           cd source
           docker run shell-bot
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/$username/shellbot-workflow loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.GHUSER }}\r\"
              expect \"Password\"
              send \"${{ secrets.GHPASS }}\r\"
              expect \"main -> main\"
              set timeout -10
              interact"
              
